config/routes.rb
Rails.application.routes.draw do
  get 'publishers/new'

  get 'publishers/create'

  get 'publishers/update'

  get 'publishers/edit'

  get 'publishers/destroy'

  get 'publishers/index'

  get 'publishers/show'

  get 'publishers/new'

  get 'publishers/create'

  get 'publishers/update'

  get 'publishers/edit'

  get 'publishers/destroy'

  get 'publishers/index'

  get 'publishers/show'

  get 'authors/new'

  get 'authors/create'

  get 'authors/update'

  get 'authors/edit'

  get 'authors/destroy'

  get 'authors/index'

  get 'authors/show'

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'books/new'

  get 'books/create'

  get 'books/update'

  get 'books/edit'

  get 'books/destroy'

  get 'books/index'

  get 'books/show'

  get 'about/index'

  get 'about' => 'about#index'

  root 'books#index'

  resources :books
  resources :categories
  resources :authors
  resources :publishers

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many:books
	validates :first_name, presence: true
	validates :last_name, presence: true
end

app/models/book.rb
class Book < ActiveRecord::Base

	belongs_to :category	
	belongs_to :author
	belongs_to :publisher


end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many:books
	validates :name, presence: true, length: {minimum:3} 
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
	has_many:books
	validates :name, presence: true, length: {minimum:5}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  	@page_title = 'About us'
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = 'Add author'
    @author = Author.new
  end

  def create
     @author = Author.new(author_params)
    if @author.save
      flash[:notice] = 'Succesfully new author created'
    redirect_to authors_path
    else
      flash[:notice] = 'Error creating new author'
    render 'new'
    end  
  end

  def update
    @author = Author.find(params[:id])
    @author.update(author_params)
    flash[:notice] = 'Author updated'
    redirect_to authors_path
  end

  def edit
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    flash[:notice] = 'Succesfully author removed'
    redirect_to authors_path 
  end

  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
    @authors = Author.all
    @books = Book.all
    @categories = Category.all
  end
  
  private
    def author_params
    params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = 'Add book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
  	@book = Book.new(book_params)
  	@book.save
  	flash[:notice] = 'Book Added'
  	redirect_to books_path
  end

  def update
  	@book = Book.find(params[:id])
  	@book.update(book_params)
  	flash[:notice] = 'Book updated'
  	redirect_to books_path
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	flash[:notice] = 'Book deleted'
  	redirect_to books_path
  end

  def index
  	@books = Book.all
	  @categories = Category.all
  end

  def show
  	@book = Book.find(params[:id])
  	@categories = Category.all
  end

  private
    def book_params
    params.require(:book).permit(:title, :coverpath, :category_id, :author_id, :publisher_id, :year, :isbn, :format, :pages, :excerpt, :price, :buy)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Add category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Succesfully new category created'
    redirect_to categories_path
    else
      flash[:notice] = 'Error creating new category'
    render 'new'
    end  
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    flash[:notice] = 'Category updated'
    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
      flash[:notice] = 'Succesfully category removed'
    redirect_to categories_path  
  end

  def index
  @categories = Category.all
  end

  def show
  @category = Category.find(params[:id])
  @categories = Category.all
  @books = Book.all
  end
    private
    def category_params
    params.require(:category).permit(:name)
    end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = 'Add publisher'
    @publisher = Publisher.new
  end

  def create
     @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = 'Succesfully new publisher created'
    redirect_to publishers_path
    else
      flash[:notice] = 'Error creating new publisher'
    render 'new'
    end  
  end

  def update
    @publisher = Publisher.find(params[:id])
    @publisher.update(publisher_params)
    flash[:notice] = 'Publisher updated'
    redirect_to publishers_path
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy
    flash[:notice] = 'Succesfully publisher removed'
    redirect_to publishers_path 
  end

  def index
    @publishers = Publisher.all
  end

  def show
  end

    private
    def publisher_params
    params.require(:publisher).permit(:name)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>Find me in app/views/about/index.html.erb</p>
<BR />

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= form_for @author do |f| %>

	<!-- check for errors -->
	<% if @author.errors.any? %>
		<% @author.errors.full_messages.each do |msg| %>
			<!-- show errors -->
			<div class='alert alert-danger'><%= msg %></div>
		<% end %>
	<% end %>

	<!-- main form -->
	<div class='form-group'>
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name, class:'form-control' %><br />
	</div>
	<%= f.submit 'Submit', class:'btn btn-primary' %>
	<%= link_to 'Cancel', authors_path, class:'btn btn
	default' %>
	
<% end %>

app/views/authors/index.html.erb
<h1>Authors index</h1>


<table class='table table-striped'>
	<tr>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Actions</th>
	</tr>
	<% @authors.each do |author| %>
	<tr>
		<td><%= author.first_name %></td>
		<td><%= author.last_name %></td>
		<td><%= link_to 'Edit', edit_author_path(author.id) %> | 
			<%= link_to 'Delete', author_path(author.id), method: :destroy, data: {confirm: 'Are you sure to delete this author?'} %>
		</td>
	</tr>
	<% end %>
</table>

app/views/authors/new.html.erb
<h1>Add new author</h1>

<%= form_for @author do |f| %>

	<!-- check for errors -->
	<% if @author.errors.any? %>
		<% @author.errors.full_messages.each do |msg| %>
			<!-- show errors -->
			<div class='alert alert-danger'><%= msg %></div>
		<% end %>
	<% end %>

	<!-- main form -->
	<div class='form-group'>
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name, class:'form-control' %><br />
	</div>
	<%= f.submit 'Submit', class:'btn btn-primary' %>
	<%= link_to 'Cancel', authors_path, class:'btn btn
	default' %>
	
<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= form_for @book do |f| %>
	<div class='form-group'>
		<%= f.label :title %><br />
		<%= f.text_field :title, class:'form-control' %><br />
	</div>
		<div class='form-group'>
		<%= f.label :coverpath %><br />
		<%= f.text_field :coverpath, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :category %><br />
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select one'}, class:'form-control' %><br /><br />
	</div>
	<div class='form-group'>
		<%= f.label :author %><br />
		<%= f.select :author_id, Author.all.collect{|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => 'Select one'}, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :publisher %><br />
		<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select one'}, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :year %><br />
		<%= f.text_field :year, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :isbn %><br />
		<%= f.text_field :isbn, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :format %><br />
		<%= f.text_field :format, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :pages %><br />
		<%= f.number_field :pages, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :excerpt %><br />
		<%= f.text_area :excerpt, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :price %><br />
		<%= f.text_field :price, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :buy %><br />
		<%= f.text_field :buy, class:'form-control' %><br />
	</div>
	<%= f.submit 'Submit', class:'btn btn-primary' %>
	<%= link_to 'Cancel', books_path, class:'btn btn-default' %>
	
<% end %>

app/views/books/index.html.erb
<div id='books-index'>

<% @books.each_slice(4) do |book| %>
	<div class='row'>
	<% book.each do |book| %>
		<div class='col-md-3 col-sm-3'>
		<h3><%= book.title %></h3>
		<%= image_tag(book.coverpath) %>
		<%= link_to 'Read more', book_path(book), class:'btn btn-primary' %>
		</div>
	<% end %>
<% end %>	
		<div class='col-md-3 col-sm-3'>
			<h3>Ruby on Rails Bible</h3>
			<%= image_tag('bookcovers/2.jpg') %>
			<%= link_to 'Read more', book_path(2), class:'btn btn-primary' %>
		</div>
		<div class='col-md-3 col-sm-3'>
			<h3>Ruby on Rails Power Bible</h3>
			<%= image_tag('bookcovers/3.jpg') %>
			<%= link_to 'Read more', book_path(3), class:'btn btn-primary' %>
		</div>
		<div class='col-md-3 col-sm-3'>
			<h3>Ruby on Rails Power Bible</h3>
			<%= image_tag('bookcovers/4.jpg') %>
			<%= link_to 'Read more', book_path(4), class:'btn btn-primary' %>
		</div>
	</div>
	<div class='row'>
		<div class='col-md-3 col-sm-3'>
			<h3>Ruby on Rails Power Bible</h3>
			<%= image_tag('bookcovers/1.jpg') %>
			<%= link_to 'Read more', book_path(1), class:'btn btn-primary' %>
		</div>
		<div class='col-md-3 col-sm-3'>
			<h3>Ruby on Rails Power Bible</h3>
			<%= image_tag('bookcovers/6.jpg') %>
			<%= link_to 'Read more', book_path(6), class:'btn btn-primary' %>
		</div>
		<div class='col-md-3 col-sm-3'>
			<h3>Ruby on Rails Power Bible</h3>
			<%= image_tag('bookcovers/7.jpg') %>
			<%= link_to 'Read more', book_path(7), class:'btn btn-primary' %>
		</div>
		<div class='col-md-3 col-sm-3'>
			<h3>Ruby on Rails Power Bible</h3>
			<%= image_tag('bookcovers/8.jpg') %>
			<%= link_to 'Read more', book_path(8), class:'btn btn-primary' %>
		</div>
	</div>
	<div class='row'>
		<div class='col-md-3 col-sm-3'>
			<h3>Ruby on Rails Power Bible</h3>
			<%= image_tag('bookcovers/9.jpg') %>
			<%= link_to 'Read more', book_path(9), class:'btn btn-primary' %>
		</div>
		<div class='col-md-3 col-sm-3'>
			<h3>Ruby on Rails Power Bible</h3>
			<%= image_tag('bookcovers/10.jpg') %>
			<%= link_to 'Read more', book_path(10), class:'btn btn-primary' %>
		</div>
		<div class='col-md-3 col-sm-3'>
			<h3>Ruby on Rails Power Bible</h3>
			<%= image_tag('bookcovers/11.jpg') %>
			<%= link_to 'Read more', book_path(11), class:'btn btn-primary' %>
		</div>
		<div class='col-md-3 col-sm-3'>
			<h3>Ruby on Rails Power Bible</h3>
			<%= image_tag('bookcovers/12.jpg') %>
			<%= link_to 'Read more', book_path(12), class:'btn btn-primary' %>
		</div>
	</div>		
</div>

app/views/books/new.html.erb
<h1>Add new Book</h1>

<%= form_for @book do |f| %>
	<div class='form-group'>
		<%= f.label :title %><br />
		<%= f.text_field :title, class:'form-control' %><br />
	</div>
		<div class='form-group'>
		<%= f.label :coverpath %><br />
		<%= f.text_field :coverpath, class:'form-control' %><br />
	</div>

<!-- select field -->
	<div class='form-group'>
		<%= f.label :category %><br />
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select one'}, class:'form-control' %><br /><br />
	</div>
	<div class='form-group'>
		<%= f.label :author %><br />
		<%= f.select :author_id, Author.all.collect{|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => 'Select one'}, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :publisher %><br />
		<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select one'}, class:'form-control' %><br />
	</div>
<!-- end select field -->

	<div class='form-group'>
		<%= f.label :year %><br />
		<%= f.text_field :year, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :isbn %><br />
		<%= f.text_field :isbn, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :format %><br />
		<%= f.text_field :format, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :pages %><br />
		<%= f.number_field :pages, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :excerpt %><br />
		<%= f.text_area :excerpt, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :price %><br />
		<%= f.text_field :price, class:'form-control' %><br />
	</div>
	<div class='form-group'>
		<%= f.label :buy %><br />
		<%= f.text_field :buy, class:'form-control' %><br />
	</div>
	<%= f.submit 'Submit', class:'btn btn-primary' %>
	<%= link_to 'Cancel', books_path, class:'btn btn-default' %>
	
<% end %>

app/views/books/show.html.erb
<div id='book-show'>
	<h2><%= @book.title %></h2>
	<div class='books-show-left'>
		<%= image_tag(@book.coverpath) %>
	</div>
	<div class='books-show-right'>
		<h3>Book info:</h3>
		<ul>
			<li><strong>Category: </strong><%= @book.category.name %></li>
			<li><strong>Author: </strong><%= @book.author.first_name %> <%= @book.author.last_name %></li>
			<li><strong>Publisher: </strong><%= @book.publisher.name %></li>
			<li><strong>Year: </strong><%= @book.year %>2015</li>
			<li><strong>ISBN: </strong><%= @book.isbn %></li>
			<li><strong>Format: </strong><%= @book.format %></li>
			<li><strong>Pages: </strong><%= @book.pages %></li>
		</ul>
		<%= link_to 'Buy for only ' +@book.price, @book.buy, class:'btn btn-sucess', target:'blank' %>
	</div>
	<div class='clearfix'></div>
	<h4>Excerpt</h4>
	<p><%= @book.excerpt %></p>

	<h3>Administration functions</h3>
	<%= link_to 'Edit', edit_book_path(@book[:id]) %> | <%= link_to 'Delete', book_path(@book[:id]), method: :delete, data: {confirm:'Are you sure?'} %>

</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Edit category</h1>

<%= form_for @category do |f| %>

	<!-- check for errors -->
	<% if @category.errors.any? %>
		<% @category.errors.full_messages.each do |msg| %>
			<!-- show errors -->
			<div class='alert alert-danger'><%= msg %></div>
		<% end %>
	<% end %>

	<!-- main form -->
	<div class='form-group'>
		<%= f.label :name %><br />
		<%= f.text_field :name, class:'form-control' %><br />
	</div>
	<%= f.submit 'Submit', class:'btn btn-primary' %>
	<%= link_to 'Cancel', categories_path, class:'btn btn
	default' %>
	
<% end %>

app/views/categories/index.html.erb
<h1>Categories index</h1>

<table class='table table-striped'>
	<tr>
		<th>Name</th>
		<th>Actions</th>
	</tr>
	<% @categories.each do |category| %>
	<tr>
		<td><%= category.name %></td>
		<td><%= link_to 'Edit', edit_category_path(category.id) %> | 
			<%= link_to 'Delete', category_path(category.id), method: :destroy, data: {confirm: 'Are you sure to delete this category?'} %>
		</td>
	</tr>
	<% end %>
</table>

app/views/categories/new.html.erb
<h1>Add new category</h1>

<%= form_for @category do |f| %>

	<!-- check for errors -->
	<% if @category.errors.any? %>
		<% @category.errors.full_messages.each do |msg| %>
			<!-- show errors -->
			<div class='alert alert-danger'><%= msg %></div>
		<% end %>
	<% end %>

	<!-- main form -->
	<div class='form-group'>
		<%= f.label :name %><br />
		<%= f.text_field :name, class:'form-control' %><br />
	</div>
	<%= f.submit 'Submit', class:'btn btn-primary' %>
	<%= link_to 'Cancel', categories_path, class:'btn btn
	default' %>
	
<% end %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/assets/images/favicon.ico" type="image/x-icon" />
    <%= favicon_link_tag %>

  <title><%= @page_title ? @page_title : '' %> | The bookstore </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">THE BOOKSTORE</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller]=='books' ? 'active' : '' %>"><%= link_to 'Home', root_path %></li>
            <li class="<%= params[:controller]=='about' ? 'active' : '' %>"><%= link_to 'About', about_path %></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Add New <span class="caret"></span></a>
          <ul class="dropdown-menu navbar-right" role="menu">
            <li><%= link_to 'Author', new_author_path %></li>
            <li><%= link_to 'Category', new_category_path %></li>
            <li><%= link_to 'Book', new_book_path %></li>
            <li><%= link_to 'Publisher', new_publisher_path %></li>
         </ul>
      	</li>
      	<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage <span class="caret"></span></a>
          <ul class="dropdown-menu navbar-right" role="menu">
            <li><%= link_to 'Authors', authors_path %></li>
            <li><%= link_to 'Categories', categories_path %></li>
            <li><%= link_to 'Books', books_path %></li>
            <li><%= link_to 'Publishers', publishers_path %></li>
         </ul>
      	</li>
        </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <header>
    <div class="container">
      <h1>The bookstore <small> <%= @page_title? @page_title : 'welcome' %></small></h1>
    </div>
    </header>
    
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-8">

        <!-- alerts and messages -->
        <% if flash[:notice] %>
			<div class='alert alert-success'>
				<%= flash[:notice] %> </div>
		<% end %>
		<% if flash[:alert] %>
			<div class='alert alert-danger'>
				<%= flash[:alert] %> </div>
		<% end %>

        <!-- main body -->
          <%= yield %>
        </div>

        <!-- partials -->
        <div class="col-md-4">
        	<%= render 'layouts/partials/sidebar' %>
        </div>
      </div>
    </div>
  </section>

  <footer>
  	<div class="container">
  		<p>Copyright &copy; <%= Time.now.year %>, All Rights Reserved MUFICATA RTDI SL</p>
  	</div>
  </footer>
</body>
</html>

app/views/layouts/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
	<div class='well'>
		<h3>Location info</h3>
		<ul>
			<li>THE BOOKSTORE</li>
			<li>Carrer de València, 18</li>
			<li>08006 Barcelona</li>
			<li>932 15 36 13</li>
			<li>10:30-21:00</li>
		</ul>
	</div>
<% end %>

<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
	<div class="list-group">
		<% @categories.each do |category| %>
			<%= link_to category.name, category_path(category.id), class:'list-group-item' %>
		<% end %>
	</div>
<% end %>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
	<div class='well'>
		<h3>Location info</h3>
		<ul>
			<li>THE BOOKSTORE</li>
			<li>Carrer de València, 18</li>
			<li>08006 Barcelona</li>
			<li>932 15 36 13</li>
			<li>10:30-21:00</li>
		</ul>
	</div>
<% end %>

<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
	<div class="list-group">
		<% @categories.each do |category| %>
			<%= link_to category.name, category_path(category.id), class:'list-group-item' %>
		<% end %>
	</div>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h1>Edit Publisher</h1>

<%= form_for @publisher do |f| %>

	<!-- check for errors -->
	<% if @publisher.errors.any? %>
		<% @publisher.errors.full_messages.each do |msg| %>
			<!-- show errors -->
			<div class='alert alert-danger'><%= msg %></div>
		<% end %>
	<% end %>

	<!-- main form -->
	<div class='form-group'>
		<%= f.label :name %><br />
		<%= f.text_field :name, class:'form-control' %><br />
	</div>
	<%= f.submit 'Submit', class:'btn btn-primary' %>
	<%= link_to 'Cancel', publishers_path, class:'btn btn
	default' %>
	
<% end %>

app/views/publishers/index.html.erb
<h1>Publishers index</h1>

<table class='table table-striped'>
	<tr>
		<th>Name</th>
		<th>Actions</th>
	</tr>
	<% @publishers.each do |publisher| %>
	<tr>
		<td><%= publisher.name %></td>
		<td><%= link_to 'Edit', edit_publisher_path(publisher.id) %> | 
			<%= link_to 'Delete', publisher_path(publisher.id), method: :destroy, data: {confirm: 'Are you sure to delete this publisher?'} %>
		</td>
	</tr>
	<% end %>
</table>